### ISSUE TITLE
Add CI workflow to require labels for PRs

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#108]
As per the discussion in https://github.com/celestiaorg/quantum-gravity-bridge/pull/106#issuecomment-1087539242 , we need to add the following [workflow](https://github.com/marketplace/actions/require-labels) to require PRs to have a minimum of 1 label.

**Comment by liamsi** [comment]
nice, do you mind posting this approach to #eginereeing? I think we should use this in all repos! (cc @Bidon15 )

**Comment by SweeXordious** [comment]
sure
