### ISSUE TITLE
Transfer or close non-contract issues

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/quantum-gravity-bridge#115]
Open issues related to the [now-removed ](https://github.com/celestiaorg/quantum-gravity-bridge/pull/113) Go code should be moved to https://github.com/celestiaorg/celestia-app.

**Comment by SweeXordious** [comment]
on it

**Comment by SweeXordious** [comment]
Should be good now. Please let me know if I missed any

**Comment by adlerjohn** [comment]
#54 and #55 I'd say too?

**Comment by SweeXordious** [comment]
https://github.com/celestiaorg/quantum-gravity-bridge/issues/55 agreed :heavy_check_mark: . But for https://github.com/celestiaorg/quantum-gravity-bridge/issues/54 I think they would include changes on the smart contract also and would depend on those changes to create issues on the celestia-app side. Correct me if I am wrong please.
