### ISSUE TITLE
Contract not verifying valsets against the right checkpoint

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#120]
Currently, the QGB contract, when submitting valsets, creates the following checkpoint:
https://github.com/celestiaorg/quantum-gravity-bridge/blob/210a1fbb9a9fc3165a038d8cedfba177c67a5726/src/QuantumGravityBridge.sol#L275

The issue, is that the checkpoint is calculated using the `currentNonce` which is the latest `eventNonce`, and will never match the submitted one.

Example:
We relay the following attestations:
- Nonce 1 : Valset 1
- Nonce 2 : DC
- Nonce 3 : DC
- Nonce 4 : Valset 2

When submitting the `Valset 1` with `Nonce = 1`, the checkpoint will be calculated using `Nonce = 1`. However, when submitting `Valset 2` with `Nonce = 4`, the checkpoint, which the contract will check against, will be created using `Nonce = 3`, resulting in a wrong checkpoint.

The solution would be to keep a `LastValsetNonce` variable stored in the contract, so that when submitting the new checkpoint, it can be used to generate the validator set hash correctly.

@adlerjohn @evan-forbes

**Comment by evan-forbes** [comment]
nice find! yeah that solution makes sense to me

**Comment by SweeXordious** [comment]
yes, sounds good :+1:
