### ISSUE TITLE
Create wrapper contract for NMT

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/quantum-gravity-bridge#133]
Now that we have the implementation of the multiproof, does it make sense to create a separate contract that calls it? And we generate a go wrapper for this latter so that we use it in the verification command we're planning to have for the QGB? 
If so, I can create an issue and start working on it.

_Originally posted by @SweeXordious in https://github.com/celestiaorg/quantum-gravity-bridge/pull/131#pullrequestreview-1234745796_

**Comment by SweeXordious** [comment]
We should implement the following: https://github.com/celestiaorg/celestia-core/blob/3f3b7cc57f5cfc5e846ce781a9a407920e54fb72/types/share_proof.go#L62-L99 in this contract
