### ISSUE TITLE
Remove the square size from the `DataRootTuple`

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#154]
Currently, we have the square size as part of the `DataRootTuple`:
https://github.com/celestiaorg/quantum-gravity-bridge/blob/3cef3f5dfd37c3086fa40a6324f144595726dc16/src/DataRootTuple.sol#L15-L16

The reason for this is to be able to prove that a certain sequence, specified by a Celestium header, is part of the Celestia block.

The alternative would be to calculate the square size from row to data root inclusion proof as part of the fraud proof verification process.

As per https://github.com/celestiaorg/celestia-core/pull/1003, it would be better to remove the square size from the `DataRootTuple` and use the alternative approach to get the square size.

What do you think?

cc @adlerjohn @evan-forbes @cmwaters

**Comment by adlerjohn** [comment]
That should work, yeah. Under an assumption that the data root tuples are valid, then the data roots commit to row and column roots in a way that proofs to individual row roots or column roots also specify the square size by construction.
