### ISSUE TITLE
Maybe make the `DAVerfier` a library

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#162]
Currently, the `DAVerifier` is a contract that has one storage value: a QGB smart contract:
https://github.com/celestiaorg/quantum-gravity-bridge/blob/67c81ceca26099cdeb09ba4a40b867fa78843b18/src/DAVerifier.sol#L41-L51

Perhaps, it might make sense to pass the QGB smart contract, or its interface, as a parameter to the `verify` function and make the `DAVerifier` a library.

The downside to doing this is that users will need to deploy a contract that uses the `DAVerifier` to verify the proofs. Also, in the [`verify`](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/client/verify.go) command in Celestia-app, we will not be able to enhance it to expect an address of a `DAVerifier` already deployed. Best we will be able to do is keep it the same it is now, verifying the proof locally, and only checking if the data root was committed to in the QGB smart contract.

The upsides of making it a library are:
- One less stack level when verifying proofs
- We would be able to keep adding functionality to it like calculating the square size from proofs https://github.com/celestiaorg/quantum-gravity-bridge/issues/161, without having to think whether the functionality inside the `DAVerifier` is consistent, or should be separated to a different contract/library.

@adlerjohn what do you think?

**Comment by adlerjohn** [comment]
Yes, agree that would be better
