### ISSUE TITLE
Bump go version

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#180]
not at all. we can upgrade at any time. But I wanted to have the scripts match the exact environment as we have now, so that I am able to generate the right wrappers. Then, we can bump the versions in CI and in the dockerfile and shouldn't be an issue. I will open an issue for this

_Originally posted by @SweeXordious in https://github.com/celestiaorg/quantum-gravity-bridge/pull/179#discussion_r1301845618_

**Comment by rootulp** [comment]
I think there's a residual old Go version

https://github.com/celestiaorg/quantum-gravity-bridge/blob/bf1dd38c5ad0ef98f159fdc7d3170a19c3846db2/.github/workflows/tests.yml#L48
