### ISSUE TITLE
Investigate what to commit to

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/quantum-gravity-bridge#20]
## Summary

#4 proposed including a tuple root. An alternative would simple be including the data root. Investigate and document final decision.

## Proposal

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adlerjohn** [comment]
## Relay data root

In this scheme, the data root as it exists in the Celestia block header is relayed. The data root is the Merkle root of a binary Merkle tree of row and column roots, each of which is the root of a NMT.

Applications can use the data root by providing proofs to one or more subtree roots that correspond to the message.

### Pros

- Does not involve having to construct an additional commitment in Celestia validator nodes.

### Cons

- There is no way just by looking at message shares where one message ends and another begins. If two messages have the same namespace ID, the only way to know is to look at the transactions that paid for the message. Therefore ZK rollups will have to be able to 1) parse and understand Celestia transactions in their circuit, and 2) parse shares to extract the compactly-laid-out Celestia transaction, and optimistic rollups will have to be able to do the same in their EVM contract.

## Relay tuple root

In this scheme, a tuple root is relayed. The tuple root is the Merkle root of tuples, where each tuple contains (among other fields) a message commitment as it exists in the PayForMessage that paid for the message.

Applications can use the tuple root by providing proofs to a single leaf.

### Pros

- Applications do not have to understand Celestia transactions or the compact layout of transactions.

### Cons

- Celestia clients will have to construct a new commitment (which should be trivial in cost, just needs to be implemented).

**Comment by adlerjohn** [comment]
cc @liamsi @musalbas ☝️

**Comment by musalbas** [comment]
What was the final decision currently being implemented - relay tuple roots?

>Celestia clients will have to construct a new commitment (which should be trivial in cost, just needs to be implemented).

This would also mean that validators need to download all PayForMessage transactions. That's fine for now, but if we wanted to add fraud proofs to main Celestia state machine for example, validators wouldn't be able to take advantage of them.

**Comment by adlerjohn** [comment]
The implicit decision was to continue in the direction relaying tuple roots to avoid needing protobuf in the EVM. If there are no other immediate concerns, we can close this issue.

**Comment by musalbas** [comment]
Don't you still need to parse the PayForMessage transactions in the EVM though?

**Comment by adlerjohn** [comment]
With tuples? No, the tuple includes

> a message commitment as it exists in the PayForMessage that paid for the message.

i.e. not the actual transaction, only the `messageCommitment` field.
