### ISSUE TITLE
QGB: An Erroneous _newValidatorSetHash Renders the Bridge Unusable

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/quantum-gravity-bridge#200]
| **ID**                                                                        | 017 |
|:------------------------------------------------------------------------------|:--|
| **Finding**                                                                   | An Erroneous _newValidatorSetHash Renders the Bridge Unusable |
| **Severity**                                                                  | 4 - LOW |
| **Description**                                                               | Validator set updates are made by calling `QuantumGravityBridge.updateValidatorSet` and passing in the `_newValidatorSetHash`. <br><br>Validation of this hash occurs outside of the `QuantumGravityBridge` contract. In the event an erroneous hash is published, e.g. one missing address or an unsorted address array provided, future calls to both `updateValidatorSet` and `submitDataRootTupleRoot` will fail. |
| **Recommendation**                                                            | Compute the `_newValidatorSetHash` using `computeValidatorSetHash` as a precaution and include zero address checks when updating the validator set. |
| **Code References**                                                           | [QuantumGravityBridge.sol#L247](#) |

**Comment by SweeXordious** [comment]
The QGB operates under a 2/3 honest majority assumption. Having an invalid validator set hash being signed by more than 2/3rds of the validators means that more than 2/3rds are malicious (or there is a bug in all the orchestrators and relayer). So, this update follows this security assumption.

To be able to compute the new validator set hash in the smart contract, we would need to pass that validator set also as call data, which would make the call even more expensive and needing even more data.

I am not sure whether it's worth adding the extra check. 

cc @adlerjohn @evan-forbes

**Comment by evan-forbes** [comment]
leaving this the way it is sounds like an optimization. If there ever is a diff between the two then I think that the bridge has to halt no matter what, correct?

**Comment by SweeXordious** [comment]
> If there ever is a diff between the two then I think that the bridge has to halt no matter what, correct?

yes, 100%

**Comment by adlerjohn** [comment]
+1 to leave as is, the gas cost of posting and re-computing on-chain would be prohibitive, and doesn't change the security assumption.
