### ISSUE TITLE
QGB: No Restrictions on state_powerThreshold

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/quantum-gravity-bridge#201]
| **ID**                                                                        | 018 |
|:------------------------------------------------------------------------------|:--|
| **Finding**                                                                   | No Restrictions on state_powerThreshold |
| **Severity**                                                                  | 4 - LOW |
| **Description**                                                               | `state_powerThreshold` may be set to any uint256 value. If set too high, it becomes impossible for signature checks with `checkValidatorSignatures` to succeed. |
| **Recommendation**                                                            | When setting `state_powerThreshold`, validate it is being set within an acceptable range. |
| **Code References**                                                           | [QuantumGravityBridge.sol#L52](#) |

**Comment by SweeXordious** [comment]
Similar to https://github.com/celestiaorg/quantum-gravity-bridge/issues/200#issuecomment-1733515534, the power threshold relies on a 2/3s honest majority assumption. Also, we verify in the following that the validators signed on the same threshold:
https://github.com/celestiaorg/quantum-gravity-bridge/blob/22b310c9f06221372ade4fae80c6a368e2ae1346/src/QuantumGravityBridge.sol#L275-L277

So, an invalid value, even if it's not high, will halt the bridge. So, I don't think we need this check.

**Comment by adlerjohn** [comment]
It would be nice if this invariant was documented in the code.
