### ISSUE TITLE
Look into removing the `BRIDGE_ID`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/quantum-gravity-bridge#71]
Since we're a one way bridge, we might be able to remove the `BRIDGE_ID` that is normally used to prevent replay attacks. We should further investigate the consequences of removing it.

**Comment by evan-forbes** [comment]
todo: move to new repo

**Comment by rootulp** [comment]
> todo: move to new repo

Likely https://github.com/celestiaorg/quantum-gravity-bridge/search?q=BRIDGE_ID . Unfortunately, I don't have permission to transfer this issue to that repo. Perhaps @SweeXordious does?

**Comment by SweeXordious** [comment]
I think by *new repo*, Evan means the new repo we will create to contain the new orchestrator and relayer implementation. Right, @evan-forbes ?

**Comment by evan-forbes** [comment]
yeah
