### ISSUE TITLE
Create a new tag for the latest master

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/quantum-gravity-bridge#89]
Currently, when referring to the QGB repo from a Go project, it gets the `v1.0.3` which is too old.
We should create a new tag `v1.1.0` which refers to the latest master.

**Comment by SweeXordious** [comment]
@adlerjohn What do you think ?

**Comment by adlerjohn** [comment]
What parts of the Go code in this repo are needed externally?

**Comment by SweeXordious** [comment]
We currently have dependency on this: https://github.com/celestiaorg/quantum-gravity-bridge/tree/master/orchestrator/ethereum/keystore
But, I am still not sure whether that's the only thing we need from it or more. 
Question: Will this repo only contain solidity code ? Or can contain other stuff also?

**Comment by adlerjohn** [comment]
We're adults, so we can do whatever we want 😂

That being said, I think the understanding was that this repo would eventually contain only contract code and the Go wrappers, and all functional Go code would be moved to the app. cc @evan-forbes

**Comment by SweeXordious** [comment]
If that's the case, then we will need to have a tag or a release for this repo to get the wrappers. I just checked, we're apparently using them a bit too.

**Comment by adlerjohn** [comment]
The new wrappers are a completely breaking change, so I suggest `v2.0.0`. Thoughts @SweeXordious?

**Comment by SweeXordious** [comment]
If breaking changes, then yes makes sense. But I don't know if we really need to keep the old tags ? They only contain old code not related to our QGB... Maybe delete them and start all over at `v1.0.0`? making this the initial release

**Comment by adlerjohn** [comment]
We could do that, yes, though that means anything importing QGB Go code currently would break.

**Comment by adlerjohn** [comment]
Related before we tag: #90

**Comment by SweeXordious** [comment]
Nobody is importing anything as far as I know. It's only @evan-forbes branch in[ celestia-app](https://github.com/celestiaorg/celestia-app/pull/234). So, I guess it's no harm as it's just a dev branch and nothing really is merged.

**Comment by SweeXordious** [comment]
Cool, will work on this https://github.com/celestiaorg/quantum-gravity-bridge/issues/90, then we tag.

**Comment by evan-forbes** [comment]
let's sync on this today in the sprint, and then update here accordingly

**Comment by adlerjohn** [comment]
No longer relevant
